<?php $this->load->view('header'); ?>
    <div class="we-are-area">
        <div class="container">
            <div class="row">
                <div class="span12">
                    <div class="we-are">
                        <span class="left-shadow"></span>
                        <h3 class="we-are-head">Privacy Policy</h3>
                        <span class="right-shadow"></span>
                    </div>
                </div>
                <div class="span10 offset1">
                    <div class="man we-are-about">
                        <p>In visiting our website, please be assured that the protection of your personal data during its collection, processing and use is very important to us. Your data is protected as required by law. Information on what kind of data is gathered during your visit to the website and how it is used follows below.</p>
                        <h5>1. Collection and processing of data</h5>
                        <p>Each page view and access of a file hosted by our website is recorded. The storage serves internal system-related and statistical purposes. The following data is recorded: name of accessed file, access date and time, transferred data amount, access success notice, web browser and requesting domain.</p>
                        <p>In addition, the IP address of the requesting computer is recorded for the data transfer. This is necessary in order enable the transfer of data between the website and the requesting computer. The recorded IP address is deleted as soon as the data transfer has been completed.</p>
                        <p>Further personal information, such as your name or your e-mail address, is only recorded if you voluntarily provide this information in connection with the contact form, information requests, data or software downloads.</p>
                        <h5>2. Use and passing on of personal data</h5>
                        <p>The personal data you have provided is used exclusively for the purposes of replying to your requests and fulfilling contracts made with you, as well as for technical administration and marketing purposes such as via mail, e-mail or phone, given you have agreed to its use for these purposes. </p>
                        <p>Your personal data are only passed on to third parties or otherwise transferred if necessary to fulfil the contract, for billing purposes or if previously approved by you. No data is sold to third parties or otherwise commercially exploited. </p>
                        <p>However, by order of the appropriate authorities, we are required to provide this data in isolated cases if so necessary for criminal prosecution, averting danger, the performance of legal tasks by the German Federal Office for the Protection of the Constitution (BfV), or to enforce intellectual property rights. </p>
                        <p>You have the right to revoke your consent with effect for the future at any time. Your personal data will be deleted if you revoke your consent to its storage, if it is no longer needed for the purpose previously pursued with its storage, or if its storage is illegal for other reasons.</p>
                        <h5>3. Google Analytics</h5>
                        <p>This website uses Google Analytics, a web analytics service provided by Google, Inc. (“Google”). Google Analytics uses “cookies”, which are text files placed on your computer, to help the website analyze how users use the site. The information generated by the cookie about your use of the website (including your IP address) will be transmitted to and stored by Google on servers in the United States . Google will use this information for the purpose of evaluating your use of the website, compiling reports on website activity for website operators and providing other services relating to website activity and internet usage. Google may also transfer this information to third parties where required to do so by law, or where such third parties process the information on Google's behalf. Google will not associate your IP address with any other data held by Google. You may refuse the use of cookies by selecting the appropriate settings on your browser, however please note that if you do this you may not be able to use the full functionality of this website. The general data collection and storage by Google Analytics can always be challenged through a browser extension, available at tools.google.com/dlpage/gaoptout, with effect for the future. By using this website, you consent to the processing of data about you by Google in the manner and for the purposes set out above.</p>
                        <h5>4. Facebook Social Plugins</h5>
                        <p>Our website uses social plugins (“plugins”) provided by the social network facebook.com, operated by Facebook Inc., 1601 S. California Avenue, Palo Alto, CA 94304, USA (“Facebook”). The plugins are identifiable by a Facebook logo (white letter f on blue background or a thumb up icon) or the notice “Facebook Social Plugin”. For a full list of all social Plugins please see http://developers.facebook.com/plugins.</p>
                        <p>When you visit a page of our website that contains a social plugin, your browser establishes a direct connection to Facebook servers. Facebook directly transfers the plugin content to your browser which embeds the latter into the website, enabling Facebook to receive information about your having accessed the respective page of our website. Thus we have no influence on the data gathered by the plugin and inform you according to our state of knowledge: </p>
                        <p>The embedded plugins provide Facebook with the information that you have accessed the corresponding page of our website. If you are logged into Facebook, your visit can be assigned to your Facebook account. If you interact with the plugins, for example by clicking “Like”, or entering a comment, the corresponding information is transmitted from your browser directly to Facebook and stored by it. Even if you are not logged into Facebook, there is possibility that the plugins transmits your IP-address to Facebook. </p>
                        <p>For the information on the purpose and scope of data collection and procession by Facebook, as well as your rights in this respect and settings options for protecting your privacy please visit Facebook’s privacy policy: http://www.facebook.com/policy.php. </p>
                        <p>If you are a Facebook member and do not want Facebook to connect the data concerning your visit to our website with your member data already stored by Facebook, please log off Facebook before entering our website. Further you can block Facebook social Plugins by using add-ons for your browser, like the “Facebook Blocker“.</p>
                        <h5>5. Security advice</h5>
                        <p>By utilising all technical and organisational means at our disposal, we are always working hard to store your personal data in a way that makes it inaccessible to third parties. Complete data security cannot be guaranteed for communication via e-mail, so please be advised of sending your confidential information via "regular" mail.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php $this->load->view('footer'); ?>