<?php $this->load->view('header'); ?>
    <div class="we-are-area">
        <div class="container">
            <div class="row">
                <div class="span12">
                    <div class="we-are">
                        <span class="left-shadow"></span>
                        <h3 class="we-are-head">Terms &amp; Condition</h3>
                        <span class="right-shadow"></span>
                    </div>
                </div>
                <div class="span10 offset1">
                    <div class="man we-are-about">
                        <p>All the services of Clippingpathfamily.com  (“Clipping path family”) available on this Website for the Client, subject to the following terms and conditions.</p>
                        <p>By accessing or using the Website, or while taking any services, the Client acknowledges that he, she or it has read, understands, and agrees, without limitation or qualification, to be bound to abide by these terms and conditions and laws mentioned bellows.</p>

                        <h5>1 Definition</h5>
                        <p>When The following words and terms used anywhere in this document will convey the following meanings unless the context clearly indicates other terms. </p>

                        <p>a) Client: the natural or legal person who or which has registered at the Website and/ or has provided Clipping Path Family with an order for Services.<br>
                        b) Services: generating clipping paths, masking of images, UI Designs, Identity Designs and other graphic services provided by Clipping Path Family as advertised on the Website and in other promotional tools. <br>
                        c) Clipping path family: Clippingpathfamily.com , the legal person who has accepted the registration and/ or the order referred to under a. or who has made an offer or quotation preceding a possible order.<br>
                        d) Clipped Image(s): the outcome of one or more images after Clipping Path Family has successfully done the Services.<br>
                        e) Website: www.clippingpathfamily.com.</p>

                        <h5>2 General</h5>
                        <p>2.1 These terms and conditions apply to all offers/price quotations by Clipping path family, all agreements between Clipping Path Family and the Client, as well as all obligations ensuing from and based on such agreements.</p>
                        <p>2.2 These terms and conditions may not be amended, varied or modified except insofar as Clipping Path Family has expressly accepted them in writing. </p>
                        <p>2.3 If any provision of these terms and conditions is declared invalid, unenforceable or illegal by the courts or arbitrators, the remaining provisions of these terms and conditions should be continued in full force and effect.</p>
                        <p>2.4 When visiting and surfing the Website, creating an account on the Website or placing an order, the Client agrees with these terms and conditions.</p>
                        <p>2.5 Any other terms and conditions or provisions proposed by the Client, whether orally or in writing, shall be of no effect and the Services provided by Clipping Path Family shall not constitute acceptance of such terms and conditions or provisions, unless Clipping Path Family has expressly accepted such terms, conditions or provisions in writing.</p>
                        <p>2.6 Clipping Path Family has the right to change the content, pricing, service charges, date of publishing, images and each kind of information whenever the authority wants.  All information on the Website is provided as it is and clients should independently verify any information provided on the Website before relying upon it.</p>
                        <p>2.7 The Client is not entitled to assign or transfer to any third party any of the rights or obligations under these terms and conditions.</p>
                        <p>2.8 Clipping Path Family reserves the right to revise these terms and conditions at its own discretion. Any amendments and subsequent obligations on the part of the Client are directly applicable after notice is provided on the Website.</p>

                        <h5>3 The Services</h5>
                        <p>3.1 Clipping Path Family will provide the Services (the use of which is entirely at the Client’s risk) for the prices as mentioned on the Website: (i) if the Client is able to deliver the image(s) as a graphics file or files, in .JPEG, .GIF, .PNG, .EPS, .BMP, .PSD or .TIFF format up to a maximum of 200MB each, via the Website; or (ii) if the image(s) can be delivered through the Client’s FTP (File Transfer Protocol) and Clipping Path Family is able to transfer the image(s) (up to a maximum of 200MB each) from the Client’s FTP destination to the Website. </p>
                        <p>3.3 If the Client includes no requirements regarding the Services, the Services will occur in a standard manner meaning that the whole background will be removed from the object(s) and made white.</p>
                        <p>3.4 Upon receipt of each order, Clipping Path Family will check its contents for compliance with Clipping path family’s published standards and Clipping path family’s capacity to fulfil it. Furthermore, Clipping Path Family will check the complexity of the order and assign a complexity level to it. Each order submitted by the Client shall be subject to acceptance by Clipping Path Family and such acceptance may be withheld at the discretion of Clipping path family. After acceptance, Clipping Path Family will notify the Client by email to confirm acceptance of the order and deliver the Client a price quotation/offer. Acceptance of the offer and payment, insofar as the Client and Clipping Path Family have not agreed upon payment after delivery as mentioned in clause 4.4, must occur within 14 calendar days.</p>
                        <p>3.5 In the standard manner as described in clause 3.4, the Client has the right to refuse the images -in the application on the Website- up to a maximum of five times, without having to pay extra for correction round(s). Only in cases where the image quality is proven to be insufficient for Clipping Path Family to perform its Services, Clipping Path Family may charge the Client extra for corrections. The submitted file and the content of the submitted job shall together constitute the order of the Client. </p>

                        <p>3.6 Instead of the standard manner as described in clause 3.4, the Client could include additional requirements regarding the Services. In such case the Client has the right to refuse the images -in the application on the Website- up to a maximum of one time, without having to pay extra for the correction. In cases where the image quality is proven to be insufficient for Clipping Path Family to perform its services, Clipping Path Family may charge the Client extra for the correction round.</p>
                        <p>3.7 Upon the Client’s request, as well as in case it becomes necessary to perform the Services, the image(s) will be transformed into a different graphic file. Transforming an image into a different graphic file may affect, by way of example and not as a limitation, the quality and colour of the original image. Clipping Path Family cannot make any assurance to the Client in regard to the result or output that derives from transforming an image into a different graphic file.</p>
                        <p>3.8 The Client may cancel the order on the Website after receiving the price quotation for the Services. However, the Client may not cancel an order after notification of acceptance by Clipping Path Family as the provision of Services for that order will have commenced.</p>
                        <p>3.9 Clipping Path Family shall notify the Client by email when the Client’s order has been completed and the results are available for download from the Website. However, Clipping Path Family recommends that the Client visits his personal account regularly, as it is possible that emails do not reach their destination due to anti-spam, virus scanners and other methods of mail security. Clipping Path Family will save Clipped Images for at least 15 days after the images have been processed.</p>

                        <h5>4 Prices &amp; Payments</h5>
                        <p>4.1 Clipping Path Family will show the number of images for the Services on the invoice to the Client. The number of images for Services could be different from the number of images which the Client has uploaded on the Website due to possible rejections or service needs of images by Clipping Path Family because of, but not limited to, the size and quality. The Client shall bear the risk of misunderstandings with regard to the number of images and is therefore responsible for checking the number of images on the invoice.</p>
                        <p>4.2 If Clipping path family, considering the volume of an order by the Client, agrees in writing upon payment after delivery, then the Payment must be made within offered bill cycle date ranges from (1 week, 15 days and 29/30/31 Days)   without being able to invoke any discount, compensation or suspension. In this process all the quotation will be auto approved by the application as per the agreed price.</p>
                        <p>4.3 Clipping Path Family aims to protect legitimate credit card owners and/or users of other online payment methods from fraud and therefore may report to the relevant authorities any person using or attempting to use a credit card or other online payment methods without apparent authority.</p>
                        <p>4.4 Clipping Path Family will charge the Client the prices for the Services as mentioned on the Website, unless a different or a fixed price arrangement has explicitly been provided in writing by Clipping path family. All standard prices listed on the Website are subject to change without prior notice. </p>
                        <p>4.5 If the Client does not pay within the time frame specified, the Client shall be considered in default. Clipping Path Family shall be entitled, without any notice of default, to charge interest as from the due date.  Interest shall be calculated according to the current statutory commercial interest or, if applicable, the statutory interest rate, as well as any judicial and extrajudicial charges associated with collection, which add up to 10% of the outstanding amount, with a minimum of  $100.</p>
                        <p>4.6 Each and every delivery of Clipped Images to the Client shall take place while reserving the ownership of these Clipped Images until such time as the Client has paid all that he is obliged to pay pursuant to any order, including interest and costs.</p>
                        <p>4.7 Prices and rates offered and agreed upon by Clipping Path Family will at all times be exclusive of tax and any other levies imposed by the government. All payments for the Services must be made in by online payment or payment method offered by Clipping Path Family once the job is delivered also payments can be made in a Billing cycle basis based on Mutual understating between client and clipping path family.</p>

                        <h5>5 Delivery Time</h5>
                        <p>5.1 All the orders on Clipping Path Family will be processed within 24 Hours or any given time that was fixed when the contract was started. However the delivery times are estimates only, unless it has been explicitly stated in writing by Clipping Path Family that it guarantees a definite delivery time. Clipping Path Family shall, even when a definite delivery time has been agreed, only be in default after the Client has served notice of default on Clipping Path Family.</p>
                        <p>5.2 During the execution of the Services the Client shall be obliged to do all that is reasonably necessary or desirable in order to make a timely delivery by Clipping Path Family possible, in particular by immediately answering any questions Clipping Path Family may have.  5.3 Clipping Path Family shall not be bound by an agreed delivery time if the Client requires changes to be made in the Services.</p>
                        <p>5.4. Clipping Path Family will do everything within its means to notify the Client when the specified delivery time, as shown on the Website or specified in the acceptance of the order, is unlikely to be met. The Client is still responsible for paying the amount owed for Services irrespective of the fact that Clipping Path Family is not able to meet the delivery time as shown on the Website or specified in the acceptance of the order.</p>


                        <h5>6 Warranty;  Limitation Of Liability; Indemnification</h5>
                        <p>6.1 It is guaranteed that all the clipped images will be of a high quality and it is subject to the quality of the image(s) which has (have) been delivered to Clipping path family.  THE WEBSITE IS PRESENTED “AS IS.”  CLIPPING PATH FAMILY MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND WHATSOEVER, EXPRESS OR IMPLIED, IN CONNECTION WITH THESE TERMS AND CONDITIONS OR THE WEBSITE, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT OR FITNESS FOR A PARTICULAR PURPOSE, OTHER THAN SET FORTH HEREIN.  THE CLIENT AGREES THAT CLIPPING PATH FAMILY WILL NOT BE RESPONSIBLE OR LIABLE, UNDER ANY CIRCUMSTANCES, FOR ANY:  (1) INTERRUPTION OF BUSINESS; (2) ACCESS DELAYS OR ACCESS INTERRUPTIONS TO THE WEBSITE; (3) DATA NONDELIVERY, MISDELIVERY, CORRUPTION, DESTRUCTION OR OTHER MODIFICATION; (4) LOSS OR DAMAGES OF ANY SORT INCURRED AS A RESULT OF DEALINGS WITH OR THE PRESENCE OF OFF-WEBSITE LINKS ON THE WEBSITE; (5) COMPUTER VIRUSES, SYSTEM FAILURE OR MALFUNCTION THAT MAY OCCUR IN CONNECTION WITH THE CLIENT’S USE OF THE WEBSITE, INCLUDING DURING HYPERLINK TO OR FROM THIRD-PARTY WEB SITES; OR (6) EVENTS BEYOND CLIPPING PATH FAMILY’S REASONABLE CONTROL.
                        TO THE MAXIMUM EXTENT PERMITTED BY LAW, CLIPPING PATH FAMILY WILL NOT BE LIABLE FOR ANY INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES OF ANY KIND (INCLUDING LOST PROFITS) RELATED TO THE WEBSITE REGARDLESS OF THE FORM OF ACTION WHETHER IN CONTRACT, TORT (INCLUDING NEGLIGENCE), OR OTHERWISE, EVEN IF IT HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.  IN NO EVENT SHALL ITS MAXIMUM AGGREGATE LIABILITY EXCEED THE PURCHASE PRICE OF THE ORDER.</p>
                        <p>6.2 Any claim based on any defect in the Clipped Images pursuant to these terms and conditions must be notified to Clipping Path Family in writing within seven (5) calendar days of their delivery after which the Client will be deemed to have accepted the Clipped Images as having been delivered in accordance with the order.</p>
                        <p>6.3 Clipping Path Family uses all reasonable endeavours to ensure that the Website remains available at all times. However, Clipping Path Family cannot guarantee that the Website will operate continuously or will be error free. Clipping Path Family therefore accepts no liability for any failure or non-availability of the Website and/or any failure or non-availability for downloading the Clipped Images as mentioned under clause 3.9. Furthermore Clipping Path Family accepts no liability for delay in the Services which is caused by images which do not meet the requirements as mentioned in clause 3.1.</p>
                        <p>6.4 Any failure on the part of Clipping Path Family in the performance of the Services which is the result of viruses, Trojan horses, worms, time bombs, cancelbots, corrupted files or any other similar problem shall not be imputed to Clipping Path Family and shall therefore not give the Client the right to set aside the contract or the right to damages.</p>
                        <p>6.5 By submitting any order the Client acknowledges that he, she or it has not relied on any statement, warranty or representation other than those which are made in these terms and conditions.</p>

                        <h5>7 Intellectual Properties</h5>
                        <p>7.1 Clipping Path Family authority, the affiliates and the licensors reserve the rights of all the content of the Website, including but not limited to text, design, graphics, logos, images, data compilations, software and interfaces and is protected by U.S. and international copyright laws.</p>
                        <p>7.2 After the Client has paid and downloaded the Clipped Images, the copyright of the Clipped Images is automatically transferred to the Client. If payment has not occurred, Clipping Path Family remains the copyright owner of the Clipped Images. </p>
                        <p>7.3 The trademark Clippingpathfamily.com and the logo of Clipping Path Family are trademarks of Clipping Path Family or its affiliates, and may not be used without the prior written consent of Clipping path family. All other trademarks not owned by Clipping Path Family or its affiliates that are used on the Website are the property of their respective proprietors.</p>
                        <p>7.4 Clipping Path Family grants Client a limited, revocable, and nonexclusive license to access and make personal use of the Website.  The limited license set forth in this Section does not include the right to:  (1) use, modify or download the Website or its contents other than as set forth herein; (2) create any derivative work based on either the Website or its content; (3) collect account information for the benefit of another party; (4) use any meta tags or any other “hidden text” utilizing Clipping path family’s name or the trademarks without Clipping path family’s express written consent; or (5) use software robots, spiders, crawlers, or similar data gathering and extraction tools, or take any other action that may impose an unreasonable burden or load on Clipping path family’s infrastructure.  Any unauthorized use by the Client of the Website terminates the limited license set forth in this Section without prejudice to any other remedy provided by applicable law.</p>
                        <p>7.5 Except as set forth in the limited license below, or as required under applicable law, neither the content, the trademarks, nor any other portion of the Website may be used, reproduced, duplicated, copied, sold, resold, accessed, modified, or otherwise exploited, in full or in part for any purpose without Clipping path family’s prior written consent.</p>
                        <p>7.6 If the Client provides Clipping Path Family with images, it represents and warrants that it owns or otherwise controls the rights to its images and that the images do not infringe any intellectual property rights of third-parties.  The Client further represents and warrants that such images do not constitute or contain software viruses, commercial solicitation, chain letters, mass mailings, or any form of “spam”.  The Client may not use a false e-mail address, impersonate any person or entity, or otherwise mislead Clipping Path Family as to the origin of any images.  The Client agrees to indemnify Clipping Path Family for all claims arising from the Client’s claims to any rights in any images.  The Client agrees to defend, indemnify and hold Clipping Path Family harmless, for any loss, damages, or costs, including reasonable attorneys’ fees, resulting from any third-party claim, action, or demand resulting from the Client’s use of the Website, including any claim for infringement of intellectual property rights of third-parties.  The Client also agrees to indemnify Clipping Path Family for any loss, damages, or costs, including reasonable attorneys’ fees, resulting from the Client’s use of software robots, spiders, crawlers, or similar data gathering and extraction tools, or any other action the Client takes that imposes an unreasonable burden or load on Clipping path family’s infrastructure.</p>

                        <h5>8 Privacy</h5>
                        <p>8.1 Any information that the Client provides to Clipping Path Family will be kept confidential and will be used only to support the Client’s customer relationship with Clipping path family. Clipping Path Family shall not disclose or sell information about the Client to any third party except in connection with a sale of the whole or part of the business of Clipping path family.</p>
                        <p>8.2 Clipping Path Family may use such personal data for mailings, support and general correspondence regarding the Services. If the Client prefers not to receive such communications from clipping path family, the client should notify Clipping Path Family by email to info@Clippingpathfamily.com.</p>
                        <p>8.3 Before the Client places his first order the Client will be asked to provide his name, email address and other personal information necessary for Clipping Path Family to fulfill the Services for the Client and/or enhance the Client’s visit to the Website. </p>
                         
                        <h5>9 Security</h5>
                        <p>9.1 Clippingpathfamily.com will uses "cookies" to identify users of the Website and personalize their visit by customizing web pages for them and for collecting user information to enable Clipping Path Family to provide the Services and fulfill the obligations towards the Client.</p>
                        <p>9.2 Clipping Path Family takes reasonable steps to ensure that unauthorized third parties do not access data transmitted electronically to Clipping Path Family or by Clipping Path Family via the Website. However Clipping Path Family cannot guarantee that such access will not happen. Consequently, the Client accepts the risk that data transmitted electronically by Clipping Path Family or to Clipping Path Family via the Website may be intercepted or accessed by third parties who are unauthorized by Clipping Path Family to access such data.</p>
                        <p>9.3 The Client acknowledges that the Client is responsible for the protection of his, her or its computer system, hardware, software and data and those of third parties who may access or otherwise be connected to the computer system of the Client. Consequently, the Client accepts responsibility for ensuring that all emails, programs or other data downloaded or otherwise received from the Website or from Clipping Path Family are free from viruses, worms, Trojans and all other forms of malicious code before using the same.</p>
                        <p>9.4 Clipping Path Family tracks the geographical locations of customers to avoid fraudulent activities.</p>
                         
                        <h5>10 Confidentiality</h5>
                        <p>All the information should be kept confidential and both parties agree that (including trade secrets and proprietary information), the information may be disclosed to them by the other party pursuant to these terms and conditions. Both parties also agree that they shall not, without the prior written consent of the disclosing party, use any confidential information for their own purposes or disclose it to any third party other than for the performance of the Services, provided that the receiving party shall have no obligations under this article to the extent that such information is public knowledge or is already known to the receiving party at the time of disclosure or subsequently becomes public knowledge other than by breach of these terms and conditions or subsequently comes lawfully into the possession of the receiving party from a third party.</p>

                        <h5>11 Force Majeure</h5>
                        <p>Force majeure is understood to be any circumstance beyond the control of the parties, as a result of which compliance with the agreement can no longer be required in all reasonableness. In the above context, by way of example, the following events are also considered to be cases of force majeure: any malfunctions, which may or may not be temporary, at the premises of one of the parties, or circumstances preventing normal implementation of the agreement, including but not limited to strikes, insurrection, lock-outs, intervention by a higher authority, acts of terror, state of war and/or siege, fire, natural disasters, epidemics, extreme weather conditions and similar circumstances.</p>

                        <h5>12 Miscellaneous</h5>
                        <p>The Client must have to be acknowledged and agreed that these terms and conditions constitute the complete and exclusive agreement between the parties concerning the Client’s use of the Website, and supersede and govern all prior proposals, agreements, or other communications.</p>

                        <p>Any kind of changes posted on the website will be effective immediately. The Client’s continued use of the Website constitutes the Client’s agreement to all such terms and conditions.  Clipping Path Family may, with our without prior notice, terminate any of the rights granted by these terms and conditions.  The Client shall comply immediately with any termination or other notice, including, as applicable, by ceasing all use of the Website.</p>

                        <p>Nothing contained in these terms and conditions shall be construed as creating any agency, partnership, or other form of joint enterprise between Clipping Path Family and the Client.  Clipping path family’s failure to require the Client’s performance of any provision hereof shall not affect the full right to require such performance at any time thereafter, nor shall Clipping path family’s waiver of a breach of any provision hereof be taken or held to be a waiver of the provision itself.  In the event that any provision of these terms and conditions shall be unenforceable or invalid under any applicable law or be so held by any arbitral award or applicable court decision, such unenforceability or invalidity shall not render these Terms and Conditions unenforceable or invalid as a whole. 
                        Clipping Path Family reserves the right, in its sole discretion, to change these terms and conditions at any time by posting the changes on the Website.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php $this->load->view('footer'); ?>